name: CI

on:
  push:
    branches: [ master, main, development, uesgraphs_githubci, version_2.1.1 ]
  pull_request:
    branches: [ master, main, development, uesgraphs_githubci, version_2.1.1 ]

jobs:
  ci:
    uses: RWTH-EBC/ci_templates/.github/workflows/ci_pipeline.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.UESGRAPHS_GITHUB_CI }}
      
    with:
      PYTHON_VERSION:  "3.11"
      PYTHON_TEST_MATRIX: '["3.9", "3.10", "3.11", "3.12", "3.13"]'
      USE_PYLINT: false
      USE_RUFF: false
      BUILD_PACKAGE: false
      GENERATE_DOCUMENTATION: true
      GH_PAGES: true
      GH_PAGES_BRANCH: "gh-pages"
      GH_PAGES_DIR: "/tmp/gh-pages"
      DOCS_PATH: "docs"
      CREATE_PAGES_ON_FAILURE: true
      EXECUTE_TESTS: true
      EXECUTE_COVERAGE_TEST: true
      PYPI_RELEASE: true
      CONVERT_EXAMPLES: false
      